title:         "OS222: Operating Systems 2022-2"
name:          "Ferry"
author:        "ferryhieronimus"
year:          "2022"
myloglink:     "/TXT/mylog.txt"
mygithublink:  "https://github.com/ferryhieronimus/os222/"
encoding:      UTF-8
markdown:      kramdown
input:         GFM
hard_wrap:     false
github:        [metadata]
